version: "3.9"
services:
  app1:
    image: ${NEXUST_REPO_HOST}:8082/repository/app/app1:${VERSION}
    build:
      dockerfile: ./app1/Dockerfile
  app2:
    image: ${NEXUST_REPO_HOST}:8082/repository/app/app2:${VERSION}
    build:
      dockerfile: ./app2/Dockerfile
  tests:
    image: ${NEXUST_REPO_HOST}:8082/repository/app/tests:${VERSION}
    build:
      dockerfile: ./tests/Dockerfile
      