version: "3"

networks:
  hw:
    external: true

services:
  server:
    image: gitea/gitea:1.17.4
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - hw
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - hw
    volumes:
      - ./postgres:/var/lib/postgresql/data
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
    - ./jenkins:/var/jenkins_home
    - //var/run/docker.sock:/var/run/docker.sock
    - ./infra/docker/docker:/usr/bin/docker 
    - ./infra/docker-compose/docker-compose:/usr/bin/docker-compose
    - ./infra/kubectl/kubectl:/usr/bin/kubectl
    - ./infra/kube/:/var/jenkins_home/.kube/
    networks:
      - hw
  nexus:
    image: sonatype/nexus3
    networks:
      - hw
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
      - "8082:8082"
      
volumes:
  nexus-data: {}